tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "mutagen-io/mutagen"
tap "rippling/rippling", "git@github.com:rippling/homebrew-rippling"
# Archival front-end
brew "atool"
# Official Amazon AWS command-line interface
brew "awscli"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Programmable completion for Bash 4.2+
brew "bash-completion@2"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Manage your dotfiles across multiple diverse machines, securely
brew "chezmoi"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Collection of GNU find, xargs, and locate
brew "findutils"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU awk utility
brew "gawk"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Command-line option parsing utility
brew "gnu-getopt"
# GNU implementation of the famous stream editor
brew "gnu-sed"
# GNU version of the tar archiving utility
brew "gnu-tar"
# GNU implementation of which utility
brew "gnu-which"
# Add GitHub support to git on the command-line
brew "hub"
# Lightweight and flexible command-line JSON processor
brew "jq"
# User-friendly front-end to ssh-agent(1)
brew "keychain"
# Pager program similar to more
brew "less"
# Node version management
brew "n"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Execute binaries from Python packages in isolated environments
brew "pipx"
# Python version management
brew "pyenv"
# Pyenv plugin to manage virtualenv
brew "pyenv-virtualenv"
# File browser
brew "ranger"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Autoformat shell script source code
brew "shfmt"
# Terminal multiplexer
brew "tmux"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# JavaScript package manager
brew "yarn"
# Process YAML, JSON, XML, CSV and properties documents from the CLI
brew "yq"
# Fast file synchronization and network forwarding for remote development
brew "mutagen-io/mutagen/mutagen"
# CLI to use for SAML login within Rippling
brew "rippling/rippling/rippling-saml-login"
# GPU-accelerated terminal emulator
cask "alacritty"
# App to build and share containerized applications and microservices
cask "docker"
# Plugin for AWS CLI to start and end sessions that connect to managed instances
cask "session-manager-plugin"
