#!/usr/bin/env bash
#
# Script to ensure all bash-completion scripts are up to date
#
set -e

completions_dir="${XDG_DATA_HOME:?XDG_DATA_HOME must be defined}/bash-completion/completions"

declare -A completion_sources=(
	[git]='https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash'
	['git-prompt']="https://raw.githubusercontent.com/git/git/v$(git --version | awk '{ print $3 }' | head -n 1)/contrib/completion/git-prompt.sh"
)

for k in "${!completion_sources[@]}"; do
	echo "$k" "${completion_sources[$k]}"
	curl --progress-bar --output "$completions_dir"/"$k" "${completion_sources[$k]}"
done
